[control_plane]
k8s-worker-02 ansible_host=192.168.0.112 ansible_user=ops ansible_python_interpreter=/usr/bin/python3 hostname=k8s-worker-02

[workers]

[laptops]
k8s-worker-02

[k8s_cluster:children]
control_plane
workers
